### ISSUE TITLE
Patching users privs

### ISSUE THREAD

**Issue by S0me1-dev** [tylerdotrar/SigmaPotato#1]
Thanks for you work. Working nice via [System.Reflection] and don't need any net installs on target machines (win 10)

Is there some way to patch user privs. In my case I meet that default win 10 user have same permissions, like on your last screenshot in repo.
I have meet some tools like BypassCredGuard (here in  GitHub) to manipulate with some of those values

And maybe add some uac bypass + some obfuscation ^_^ Ofk it catched by defender and avs.

**Comment by tylerdotrar** [comment]
Glad you enjoyed it and that it's been working for you!

Sounds like for your **Bug / Issue**, it's more of a feature request for binary obfuscation to bypass AV detection.  Looking into the idea of using a CS runner, an issue might be passing arguments to the ``SigmaPotato`` memory space -- meaning I'll need to dig a bit deeper and find what Windows Defender is specifically catching.

No promises on an ETA, but I'll look into it and add it to the future versions / WIP list! 
In the meantime, I'm going to close this issue.
